Failure # 1 (occurred at 2023-05-25_09-57-56)
[36mray::ImplicitFunc.train()[39m (pid=3356747, ip=129.241.113.29, repr=hyper_search_train)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 421, in _inner
    return inner(config, checkpoint_dir=None)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 413, in inner
    return trainable(config, **fn_kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 144, in hyper_search_train
    cf.pre_train_model(copy.deepcopy(all_params), global_params)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/contrastive_framework.py", line 375, in pre_train_model
    with open(os.path.join(preprocess_root, 'pickles', f'{global_params["channel_select_function"]}_{global_params["n_channels"]}'+'split_idx_list.pkl'), 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/lhome/oskarsto/repos/master-eeg-trans/datasets/TUH/tuh_eeg_pre/pickles/adjacent_groups_2split_idx_list.pkl'
